image: docker:latest

services:
  - docker:dind

variables:
  LATEST_VER_HML: caleberios/gaia-notifica:homolog
  LATEST_VER_PROD: caleberios/gaia-notifica:latest

stages:
  - build
  - test
  - quality
  - pushImage
  - deploy

buildLocal:
  stage: build
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose build

testCheck:
  stage: test
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run gaianotifica /bin/sh -c "cd /app; npm i; npm run test"
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

staticAnalysis:
  stage: quality
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose run gaianotifica /bin/sh -c "cd /app; npm i; npm run lint"

pushHomolog:
  stage: pushImage
  only:
    - dev
  script:
    - docker build -t $LATEST_VER_HML .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_HML && docker image rm $LATEST_VER_HML

pushProd:
  stage: pushImage
  only:
    - master
  script:
    - docker build -t $LATEST_VER_PROD .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER_PROD && docker image rm $LATEST_VER_PROD

deployHomolog:
  stage: deploy
  image: google/cloud-sdk
  only:
    - dev
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete -f k8s/gaia_notifica_hml.yaml
    - kubectl apply -f k8s/gaia_notifica_hml.yaml

deployProd:
  stage: deploy
  image: google/cloud-sdk
  only:
    - master
  script:
    - source /root/.bashrc
    - gcloud auth activate-service-account --key-file ${SERVICE_ACCOUNT} --project=${GKE_PROJECT}
    - gcloud container clusters get-credentials gaia-cluster --zone us-central1-a --project gaia-240100
    - kubectl delete -f k8s/gaia_notifica.yaml
    - kubectl apply -f k8s/gaia_notifica.yaml
