version: '3'

services:
  gaianotifica:
    build: .
    restart: always
    environment:
      - ENVIRONMENT=dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3003:3003
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: aashreys/mongo-auth:latest
    command: mongod --port 27019
    ports: 
      - 27019:27019
